replicaCount: 1

image:
  # customise this to your own repository
  repository: ghcr.io/civo-learn/llm-boilerplate-app
  pullPolicy: Always
  tag: "latest"

service:
  type: LoadBalancer
  port: 80

model:
  textModel: "llama3.2:latest"
  imageModel: "x/llama3.2-vision:latest"